日 志 时 间:  2013-03-05 13:57:19,533 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Cannot access a disposed object.
Object name: 'System.ServiceModel.InstanceContext'. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.ServiceModel.InstanceContext'.
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposed()
   at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureInstanceContext(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)).


日 志 时 间:  2013-03-05 13:57:20,587 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:21,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:22,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:23,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:24,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:25,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:26,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:27,588 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:28,590 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:29,590 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:30,605 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:31,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:32,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:33,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:34,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:35,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:36,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:37,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:38,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:39,611 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:40,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:41,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:42,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:43,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:44,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:45,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:46,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:47,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:48,612 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:49,614 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:50,615 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:51,615 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:52,615 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:53,615 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:54,615 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:55,616 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:56,617 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:57,617 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:58,617 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:57:59,617 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:00,618 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:01,618 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:02,624 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:03,624 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:04,624 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:05,624 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 13:58:06,624 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 14:05:06,156 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Cannot access a disposed object.
Object name: 'System.ServiceModel.InstanceContext'. (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.ServiceModel.InstanceContext'.
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposed()
   at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureInstanceContext(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)).


日 志 时 间:  2013-03-05 14:05:07,204 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


日 志 时 间:  2013-03-05 14:05:08,205 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:123)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2067
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 123


