日 志 时 间:  2013-02-22 10:49:52,096 
日 志 级 别:  INFO
日 志 来 源:  Chatter.MetroClient.TCP.SendFileUtil.BeginSend(f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:88)
日 志 内 容:  对方取消接收
 System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Chatter.MetroClient.TCP.SendFileUtil.BeginSend() in f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:line 74


日 志 时 间:  2013-02-22 11:16:17,854 
日 志 级 别:  INFO
日 志 来 源:  Chatter.MetroClient.TCP.ReceiveFileUtil.BeginReceive(f:\code\myRepo\Chatter\MetroClient\TCP\ReceiveFileUtil.cs:101)
日 志 内 容:  对方取消发送
 System.IO.IOException: The process cannot access the file 'E:\New Text Document.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Chatter.MetroClient.TCP.ReceiveFileUtil.BeginReceive() in f:\code\myRepo\Chatter\MetroClient\TCP\ReceiveFileUtil.cs:line 76


日 志 时 间:  2013-02-22 12:31:16,796 
日 志 级 别:  ERROR
日 志 来 源:  Chatter.MetroClient.Callback.ChatterCallback.ReponseToSouceClient(f:\code\myRepo\Chatter\MetroClient\Callback\ChatterCallback.cs:255)
日 志 内 容:  接收服务器加好友相应出错
 System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Chatter.MetroClient.Callback.ChatterCallback.ReponseToSouceClient(Result result) in f:\code\myRepo\Chatter\MetroClient\Callback\ChatterCallback.cs:line 243


日 志 时 间:  2013-02-22 13:42:50,024 
日 志 级 别:  ERROR
日 志 来 源:  Chatter.MetroClient.Callback.ChatterCallback.OnSendMessage(f:\code\myRepo\Chatter\MetroClient\Callback\ChatterCallback.cs:93)
日 志 内 容:  显示信息出错
 System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Chatter.MetroClient.Callback.ChatterCallback.ReceiveCommandMessage(Message mesg) in f:\code\myRepo\Chatter\MetroClient\Callback\ChatterCallback.cs:line 104
   at Chatter.MetroClient.Callback.ChatterCallback.OnSendMessage(Message mesg) in f:\code\myRepo\Chatter\MetroClient\Callback\ChatterCallback.cs:line 88


日 志 时 间:  2013-02-22 14:39:50,906 
日 志 级 别:  INFO
日 志 来 源:  Chatter.MetroClient.TCP.SendFileUtil.BeginSend(f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:93)
日 志 内 容:  对方取消接收
 System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Chatter.MetroClient.TCP.SendFileUtil.BeginSend() in f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:line 79


日 志 时 间:  2013-02-22 14:47:34,340 
日 志 级 别:  INFO
日 志 来 源:  Chatter.MetroClient.TCP.SendFileUtil.BeginSend(f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:93)
日 志 内 容:  对方取消接收
 System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Chatter.MetroClient.TCP.SendFileUtil.BeginSend() in f:\code\myRepo\Chatter\MetroClient\TCP\SendFileUtil.cs:line 79


日 志 时 间:  2013-02-22 14:48:53,074 
日 志 级 别:  INFO
日 志 来 源:  Chatter.MetroClient.TCP.ReceiveFileUtil.BeginReceive(f:\code\myRepo\Chatter\MetroClient\TCP\ReceiveFileUtil.cs:106)
日 志 内 容:  对方取消发送
 System.IO.IOException: I/O error occurred.
   at Chatter.MetroClient.TCP.ReceiveFileUtil.BeginReceive() in f:\code\myRepo\Chatter\MetroClient\TCP\ReceiveFileUtil.cs:line 90


