日 志 时 间:  2013-04-09 16:36:27,705 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfFaulted()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:28,243 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:28,744 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:29,245 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:29,745 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:30,246 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:30,747 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:31,248 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:31,749 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:32,250 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:32,751 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:33,252 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:33,754 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:34,255 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:34,756 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:35,257 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:35,758 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:36,259 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:36,760 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:37,263 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:37,763 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:38,264 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:38,765 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:39,266 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:39,767 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:40,268 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:40,769 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:41,270 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:41,771 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:42,272 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:42,773 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:43,274 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:43,775 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:44,276 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:44,777 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:45,279 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:45,780 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:46,281 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:46,783 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:47,284 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:47,785 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:48,286 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:48,788 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:49,288 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:49,789 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:50,290 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:50,791 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:51,291 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:51,792 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:52,293 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:52,794 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:53,296 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:53,800 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:54,300 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:54,804 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:55,305 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:55,806 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:56,318 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:56,819 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:57,319 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:57,819 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:58,319 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:58,820 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:59,320 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:36:59,821 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:00,324 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:00,826 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:01,327 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:01,828 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:02,328 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:02,829 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:03,331 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:03,832 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:04,333 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:04,834 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:05,335 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:05,836 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:06,337 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:06,838 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:07,338 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:07,839 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:08,340 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:08,841 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:09,342 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:09,843 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:10,344 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:10,845 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:11,348 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:11,848 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:12,350 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:12,851 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:13,352 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:13,852 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:14,352 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:14,860 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:15,360 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:15,861 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:16,362 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:16,863 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:17,364 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:17,865 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:18,366 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:18,867 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:19,370 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:19,870 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:20,371 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:20,872 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:21,373 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:21,873 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:22,374 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:22,874 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:23,375 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


日 志 时 间:  2013-04-09 16:37:23,875 
日 志 级 别:  WARN
日 志 来 源: [8]::Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0(f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:116)
日 志 内 容:  发送心跳包出现错误
 System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at MetroClient.ChatterService.IChatter.SendHeartBeat()
   at MetroClient.ChatterService.ChatterClient.SendHeartBeat() in f:\code\myRepo\Chatter\MetroClient\Service References\ChatterService\Reference.cs:line 2107
   at Chatter.MetroClient.UI.MainWindow.<SendHeartBeat>b__0() in f:\code\myRepo\Chatter\MetroClient\UI\MainWindow.xaml.cs:line 116


